
name: 'Action Validation Checks'
author: 'ishitachawla'
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'Github Personal Access Token'
    required: true
  encoding:
    description: 'The encoding of the file.'
    default: 'utf8'
    required: false
  repositories:
    description: 'Comma separated names of repositories. For example login,webapps-deploy etc.'
    required: true
outputs:
  validationResult: 
    description: 'Validation result dictionary after applying the checks'
runs:
  using: 'node12'
  main: 'lib/main.js'
